In [2]:
import numpy as np

In [42]:
a = np.array([1, 2, 3], dtype = 'int32')
print(a)
a

[1 2 3]


array([1, 2, 3])

In [40]:
b = np.array([[1,22],[5, 4]], dtype = 'int16')
print(b)

[[ 1 22]
 [ 5  4]]


In [41]:
a.dtype

dtype('int32')

# leavel 2
 

In [43]:
# basis as python
print(a)

[1 2 3]


In [44]:
a+2

array([3, 4, 5])

In [34]:
a

array([17, 18, 19])

In [45]:
a += 2
a

array([3, 4, 5])

In [48]:
# linear alg